In [2]:
# with open('./drive.MyDrive?ReadME.md','w') as f:
#   data = f.write('*반가워요.')
#   print("저장되었습니다.")
#   !pwd

# 넘파이(numpy)

차원은 리스트 안에 상태를 말함
- ndim : 축 수(리스트가 몇개로 나눠져있는지)
- shape : 배열의 차원정보(리스트 수, 행수, 열수)
(바꿔주고 싶으면 reshpe 쓰면 됨)
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

In [21]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[3])
print(narry[2:4]) # <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [52]:
narr1 = np.array([1,2,3,4,5,6,7,8,9]) # int64
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4 5 6 7 8 9] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


## 1차원과 속성들

In [61]:
print(list(range(2,10)))
print(np.arange(2,10)) # 리스트로 감싸지 않아도 출력됨
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
# zeros : 뭐든 0으로 만들어줌. 초기화할 때 많이 씀
narr4 = np.zeros((2,2), dtype='int64') # int64를 넣어주면 ,가 사라짐
narr5 = np.ones((2,3))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.arange(0,100.5,endpoint=False,dtype='int64')
narr10 = np.arange(0,100.20)
print(narr4, narr4.ndim, narr4.dtype, narr4.shape, narr4.size, type(narr4))
print(narr5, narr5.ndim, narr5.dtype, narr5.shape, narr5.size, type(narr5))
print(narr6, narr6.ndim, narr6.dtype, narr6.shape, narr6.size, type(narr6))
print(narr7, narr7.ndim, narr7.dtype, narr7.shape, narr7.size, type(narr7))
print(narr8, narr8.ndim, narr8.dtype, narr8.shape, narr8.size, type(narr8))
print(narr8, narr9.ndim, narr9.dtype, narr9.shape, narr9.size, type(narr9))
print(narr10, narr10.ndim, narr10.dtype, narr10.shape, narr10.size, type(narr10))

TypeError: arange() got an unexpected keyword argument 'endpoint'

In [32]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape, arr1.size)

[[0 0]
 [0 0]] 2 int64 (2, 2) 4


## 2차원 배열

In [54]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1,arr1.ndim, arr1.dtype, arr1.shape, arr1.size, type(arr1))

[1 2 3 4 5 6 7 8 9] 1 int64 (9,) 9 <class 'numpy.ndarray'>


In [70]:
# reshape는 리스트로 출력. 리스트 안에 행, 열, 리스트 갯수를 정할 수 있음
# .reshape(2개 쓸 경우:행,열)
# .reshape(3개 쓸 경우:리스트수, 행,열)

arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:', arr2.ndim, '/데이터타입:', arr2.dtype, '/형태:', arr2.shape, '크기:', arr2.size, type(arr2), arr2)
print('차원:', arr3.ndim, '/데이터타입:', arr3.dtype, '/형태:', arr3.shape, '크기:', arr3.size, type(arr3), arr3)
print('차원:', arr4.ndim, '/데이터타입:', arr4.dtype, '/형태:', arr4.shape, '크기:', arr4.size, type(arr4), arr4)
print('차원:', arr5.ndim, '/데이터타입:', arr5.dtype, '/형태:', arr5.shape, '크기:', arr5.size, type(arr5), arr5)
print('차원:', arr6.ndim, '/데이터타입:', arr6.dtype, '/형태:', arr6.shape, '크기:', arr6.size, type(arr6), arr6)

차원: 2 /데이터타입: int64 /형태: (3, 3) 크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 /데이터타입: int64 /형태: (3, 3) 크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 /데이터타입: int64 /형태: (2, 5) 크기: 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 /데이터타입: int64 /형태: (5, 2) 크기: 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 /데이터타입: int64 /형태: (3, 3, 3) 크기: 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [111]:
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,22).reshape(3,7)
t5 = np.arange(1,13).reshape(4,3,1)
print(t1)
print('='*25)
print(t2)
print(t3)
print('='*25)
print(t4)
print('='*25)
print(t5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [112]:
# test
print(t1[1][2:5])
print(t4)
print(t4[1:3,2:4])
print(t4[1:3,4:6])
print(t4 % 2 ==0)

array([10, 11, 12])

In [119]:
# np 배열 연산 // shape가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [120]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [123]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(1,3)
# 스칼라와 연산
print("====스칼라와 연산====")
print(br1)
print(br2+3)
print(br2*2)
# 2D와 1D의 연산
print("====2D와 1D의 연산====")
print(br1+br2)
print(br1*br2)


====스칼라와 연산====
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[14 25 36]]
[[22 44 66]]
====2D와 1D의 연산====
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [124]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [125]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## 1.3. Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.ormal(): 분포 난수 생성

In [2]:
# randomint
import numpy as np
x = np.random.randint(1,100,size=(3,3,3))
x

array([[[ 5, 92,  4],
        [34, 32, 34],
        [85, 68, 25]],

       [[24, 59,  7],
        [93, 31, 94],
        [44, 60, 56]],

       [[54, 31, 53],
        [36, 90,  7],
        [75, 86, 61]]], dtype=int32)

In [3]:
print('평균값:',np.mean(x), '표준편차:', np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 49.629629629629626 표준편차: 28.485406462683788 최소값: 4 최대값: 94


In [7]:
print(len(x.flatten()))

27


In [9]:
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5,34,3,3,23,0,1,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
22


# 판다스(pandas)

- 시리즈(Series)- s 대문자
- 데이터프레임(DataFrame) - df 대문자

In [16]:
import numpy as np
import pandas as pd

In [26]:
# 판다스 기초
data1 = np.arange(1,6)
print(data1)
# 리스트를 넣어도 나오고 numpy해서 값이 띄워져있는 상태에 넣어도 나옴
data2 = pd.Series(data1)
print(data2, type(data2), data2.index, data2.values, data2.dtype)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=5, step=1) [1 2 3 4 5] int64


In [27]:
# 판다스 시리즈의 인덱스설정
data3 = pd.Series([1,2,3,4],index = ['a','b','c','d']) # ,dtype='float'

print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [34]:
# 판다스 시리즈 딕셔너리데이터
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
#.뭐시기 뒤에 괄호가 있으면 기능, 괄호가 없으면 특징이나옴
# population_dict.keys()
# population_dict.values()
# population_dict.items()
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근방법
print(country.loc['usa'])
print(country.iloc[3])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
32976
32976


In [33]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [91]:
# 테스트
import numpy as np
import pandas as pd

#두개의 시리즈 데이터
population = pd.Series(population_dict)
print(population)
print("GDP 시리즈 데이터:")
GDP_dict={
    'korea':169320000,
    'japan':51670000,
    'china':140925000,
    'usa':2041280000  
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('='*25)
print("데이터 프레임 생성")
country = pd.DataFrame({'population':population,'gdp':GDP})
print(country.index,country.columns)
country.index.name = "Country" # 인덱스 이름 지정
country.columns.name = "Info"# 컬럼 이름 지정
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터:
korea     169320000
japan      51670000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성
Index(['korea', 'japan', 'china', 'usa'], dtype='object') Index(['population', 'gdp'], dtype='object')
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622   51670000]
 [    141178  140925000]
 [     32976 2041280000]] (4, 2) 8 2


In [115]:
# 데이터 프레임의 요소 접근 방법, loc, iloc
country.loc['korea'],country.loc['usa']
country.iloc[2],country.iloc[1]

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population       12622
 gdp           51670000
 Name: japan, dtype: int64)

In [112]:
country.loc['korea':'japan',:'population'] # <= x <=

Info     population
Country            
korea          5182
japan         12622

In [113]:
country.iloc[0:2,:1] # <= x <

Info     population
Country            
korea          5182
japan         12622

In [79]:
# 컬럼추가
# country['test'] = [11,22,33,44]
# country = country.drop('test',axis=1) # axis 는 축
gdpper = country['gdp'] / country['population']
country['gdp-per'] = gdpper
country

Info     population           gdp       gdp-per       gdp_per
Country                                                      
korea        5182.0  1.693200e+08  32674.642995           NaN
japan       12622.0  5.167000e+07   4093.646015           NaN
china      141178.0  1.409250e+08    998.207936           NaN
usa         32976.0  2.041280e+09  61901.989326           NaN
india       14222.0  1.505050e+08  10582.548165  10582.548165

In [59]:
# 행추가 방법 1
country.loc['india'] = [14222,150505000,1212121]
country.loc['india','gdp_per'] = country.loc['india','gdp']/country.loc['india','population']
country

Info     population         gdp       gdp-per       gdp_per
Country                                                    
korea          5182   169320000  32674.642995           NaN
japan         12622    51670000   4093.646015           NaN
china        141178   140925000    998.207936           NaN
usa           32976  2041280000  61901.989326           NaN
india         14222   150505000       1212121  10582.548165

In [72]:
# 행추가 방법 2
africa = pd.Series(data = [123456,7777777],index=['population','gdp'])
country.loc['africa']=africa
# country.loc['africa','gdp_per'] = country.loc['africa','gdp']/country.loc['africa','population']
country

Info     population           gdp       gdp-per       gdp_per
Country                                                      
korea        5182.0  1.693200e+08  32674.642995           NaN
japan       12622.0  5.167000e+07   4093.646015           NaN
china      141178.0  1.409250e+08    998.207936           NaN
usa         32976.0  2.041280e+09  61901.989326           NaN
india       14222.0  1.505050e+08       1212121  10582.548165
africa     123456.0  7.777777e+06           NaN           NaN

In [73]:
# 결촉값(NaN) 확인
country.isnull().sum()

Info
population    0
gdp           0
gdp-per       1
gdp_per       5
dtype: int64

In [74]:
# 열제거 drop(이름, axis=0)
country = country.drop('africa', axis=0) # inplace = True
country

Info     population           gdp       gdp-per       gdp_per
Country                                                      
korea        5182.0  1.693200e+08  32674.642995           NaN
japan       12622.0  5.167000e+07   4093.646015           NaN
china      141178.0  1.409250e+08    998.207936           NaN
usa         32976.0  2.041280e+09  61901.989326           NaN
india       14222.0  1.505050e+08       1212121  10582.548165

In [75]:
# 테스트 1 조건
country[country['population'] > 140000]

Info     population          gdp     gdp-per  gdp_per
Country                                              
china      141178.0  140925000.0  998.207936      NaN

In [77]:
# 테스트 2 조건, 슬라이싱(loc,iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0
india       14222.0

In [1]:
# 문제 1. 프레임 만들기
import pandas as pd
score_list = {
    '이름' : ['홍길동','박철수','김영희'],
    '국어' : [80,60,70],
    '수학' : [70,70,90],
    '영어' : [80,80,80]
}
# score = pd.Series(score_list)
score = pd.DataFrame(score_list)
score

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [139]:
# 문제 2. 박철수의 국어와 수학점수만 출력
score.iloc[1:2,:3]

이름  국어  수학
1  박철수  60  70

In [5]:
# 문제 3. 수학이 70점 이상인 사람 모든 행을 출력하라
score[(score['수학']>=70)]

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [16]:
# 문제 4. 모든 과목의 평균 점수를 마지막 컬럼에 넣고 "평균"이라는 이름으로 만들어 넣어라
score['평균'] = (score['국어']+score['수학']+score['영어'])/3
print('평균',score['평균'].dtype)
score.round()

평균 float64


이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0

In [18]:
# 문제 4 (방법2)
score['평균'] = (score['국어'].astype(int) + score['수학'].astype(int)+score['영어'].astype(int))/3
print('평균',score['평균'].dtype)
score.round()

평균 float64


이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0

In [11]:
# import numpy as np
# data =  [
#     ('홍길동',80,70,80),
#     ('박철수',60,70,80),
#     ('김영희',70,90,80)
# ]
# data = np.array(data)
# data = np.array([['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80]])
# data