In [11]:
import numpy as np
array = np.array(range(10))
print(array)
print(type(array))
print(array.ndim) # ndim은 축 개수
print(array.shape) # shape는 (행 수, 열 수)인데 1차원인 경우엔 (갯수,)로 표기한다.
print(array.size) # size는 배열 안에 있는 원소 총 갯수
print(array[3:6])

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
[3 4 5]


In [19]:
arr1 = np.array([1,2,'a','b'],dtype='int') # dtype은 형식을 지정해 주는건데 서로 동일한 자료형이어야 됨
print(arr1) # dtype안해주면 str로 자동 형변환이 일어남.

ValueError: invalid literal for int() with base 10: 'a'

In [21]:
arr1 = np.array([1,2,3,4],dtype="int")
print(type(arr1))

<class 'numpy.ndarray'>


In [22]:
array = np.zeros((2,3),dtype='int64')
print(array)
array = 

[[0 0 0]
 [0 0 0]]
